### ISSUE TITLE
Set up hosting platform

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/lsp-uk#2]
Define and configure infrastructure (storage, network, compute) on which to host a modest LSP deployment.

**Comment by markgbeckett** [comment]
Assigning to Gareth for review.

**Comment by gpfrancis** [comment]
Stelios, I notice that the notes appear to describe setting up K8s manually wheras at the tech review you said you were now using Rancher?

**Comment by stvoutsin** [comment]
Gareth, the latest notes on my experiments deploying the LSP on kubernetes are  here:
https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200416-LSP-Openstack-Edinburgh.txt

I think this task was simply to write down some details and requirements (storage, network, compute) on the potential hosting platform, which can be found here:
https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200211-LSP-Hardware-Requirements.txt

**Comment by gpfrancis** [comment]
The resource requirements look perfectly sensible. In the future we probably want to look at how we automate provisioning and relative merits of doing it with OpenStack Heat and out-of-band with Ansible or similar. I don't think that's a requirement at this stage though, just something to think about.

The K8s deployment notes also look fine, certainly as far as installing Rancher and K8s, which I think is as far as is relelvant to this task.
