### ISSUE TITLE
Deploy the LSP NFS Fileserver

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/lsp-uk#22]

**Comment by stvoutsin** [comment]
Done, notes can be found here:
https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200416-LSP-Openstack-Edinburgh.txt
And scripts to setup here:
https://github.com/lsst-uk/lsp-uk/tree/master/helm/charts/fileserver

**Comment by gpfrancis** [comment]
Deployment notes look fine. Jupyter server appears to be connecting to an NFS server (presumably this one) OK.
