### ISSUE TITLE
Deploy first version of the LSP TAP Service

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/lsp-uk#23]

**Comment by stvoutsin** [comment]
Notes on issue: https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200416-LSP-Openstack-Edinburgh.txt
Demo available:
http://192.41.108.30/tap/

**Comment by gpfrancis** [comment]
Deployment notes look fine. Demo service is visible and looks like a TAP service.
