### ISSUE TITLE
Deploy first version of the LSP Landing-Page

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/lsp-uk#24]

**Comment by stvoutsin** [comment]
Notes on issue: https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200416-LSP-Openstack-Edinburgh.txt
Demo available:
http://192.41.108.30/

**Comment by gpfrancis** [comment]
Deployment notes look fine.

Minor issues:
- MOTD appears to be a placeholder, has this been tested?
- "NB documentation" and "help" appear to point to the same page.
- Privacy policy link needs customising
