### ISSUE TITLE
Setup a Reverse Proxy (Apache/Nginx?) on a Gateway node for the LSP Services

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/lsp-uk#25]

**Comment by stvoutsin** [comment]
Notes on setting up a Reverse Proxy for the LSP: https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200130-Apache-Proxy.txt

**Comment by gpfrancis** [comment]
Deployment notes look fine. Proxy appears to be working.

As noted previously, setting up HTTPS would be desirable and shoud not be difficult. In the next stage we should consider using Ansible or similar to automate deployment.
