### ISSUE TITLE
Deploy LSP FireFly web interface

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/lsp-uk#3]
... and connect to existing (e.g. WSA) TAP service.

**Comment by stvoutsin** [comment]
First version of Firefly deployed.
Demo can be found here:
http://192.41.108.30/firefly/suit/

Notes on settng it up are here:
https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200416-LSP-Openstack-Edinburgh.txt

And a a Helm chart for deploying are here:
https://github.com/lsst-uk/lsp-uk/tree/master/helm/charts/firefly

**Comment by gpfrancis** [comment]
Deployment notes look fine. Firefly appears to be installed and working.

Firefly itself appears to have a number of obvious issues, but these are probably something for the next phase of evaluation, e.g.:
- incorrect default TAP server
- "?" images lack alt or title text and lead to a 404 when clicked on
- automatically resizing panes don't work well on small screens
