### ISSUE TITLE
Fix hard-coded IP Addresses & Ports from LSP Gateway Node 

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/lsp-uk#32]
Currently, we manually set IP addresses and Ports in the LSP Gateway node Apache configuration file to point to our LSP services. If we redeploy our services these change, so we need to update the Gateway node.

We need to either automate the process of updating the Gateway configuration, or figure out how to create service aliases in Kubernetes that are updated automatically with the new ports, when redeploying

**Comment by markgbeckett** [comment]
This issue may be fixed (in latest RSP release from DM team).

**Comment by markgbeckett** [comment]
Resolved, as no longer need Proxy server. Done by NginX as part of RSP deployment.
