### ISSUE TITLE
Create a list of Docker images for Nublado

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/lsp-uk#38]
We need to create a list of all the Docker images that we want to provide as available options for the Nublado Jupyterhub service. Currently this points to a LSST DockerHub repo. Do we want this? Or do we want to use our own repo with a mix of images?

**Comment by RoyWilliams** [comment]
These are the packages that Lasair's jupyter users have used:
astropy
confluent_kafka
ephem
mysql.connector
matplotlib
mocpy
numpy
requests
scipy
wget

**Comment by markgbeckett** [comment]
To do:
- Determine whether Lasair user can use the RSP as is, or do they need additional Docker notebook image
